/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatredes2;

import java.io.File;
import javafx.scene.control.Alert;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.TreePath;

/**
 *
 * @author Nailton
 */
public class TelaChat extends javax.swing.JFrame {

    /**
     * Creates new form TelaCliente
     */
    private DefaultMutableTreeNode raiz;

    public TelaChat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_Status = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField_Mensagem = new javax.swing.JTextField();
        jButton_Enviar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList_Participantes = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel_Destinatario = new javax.swing.JLabel();
        jTabbedPane_Chat = new javax.swing.JTabbedPane();
        jScrollPane_Chat = new javax.swing.JScrollPane();
        jTextArea_HistoricoChat = new javax.swing.JTextArea();
        jScrollPane_ListaArquivos = new javax.swing.JScrollPane();
        jTree_ListaArquivos = new javax.swing.JTree();
        jButton1 = new javax.swing.JButton();
        jLabel_Status = new javax.swing.JLabel();
        jRadioButton_on = new javax.swing.JRadioButton();
        jRadioButton_Off = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_Enviar.setText("Enviar");
        jButton_Enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EnviarActionPerformed(evt);
            }
        });

        jList_Participantes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Todos", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList_Participantes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList_ParticipantesValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jList_Participantes);

        jLabel1.setText("Enviar para:");

        jLabel_Destinatario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Destinatario.setText("Todos");

        jTabbedPane_Chat.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jTabbedPane_ChatComponentAdded(evt);
            }
        });

        jTextArea_HistoricoChat.setColumns(20);
        jTextArea_HistoricoChat.setRows(5);
        jTextArea_HistoricoChat.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextArea_HistoricoChat.setEnabled(false);
        jScrollPane_Chat.setViewportView(jTextArea_HistoricoChat);

        jTabbedPane_Chat.addTab("Chat", jScrollPane_Chat);

        raiz = new DefaultMutableTreeNode("Arquivos Chat");
        JTree jTree_ListaArquivos = new JTree(raiz);
        jTree_ListaArquivos.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTree_ListaArquivosValueChanged(evt);
            }
        });
        jScrollPane_ListaArquivos.setViewportView(jTree_ListaArquivos);

        jTabbedPane_Chat.addTab("Arquivos", jScrollPane_ListaArquivos);

        jButton1.setText("Sair");

        jLabel_Status.setText("Status:");

        buttonGroup_Status.add(jRadioButton_on);
        jRadioButton_on.setSelected(true);
        jRadioButton_on.setText("On");

        buttonGroup_Status.add(jRadioButton_Off);
        jRadioButton_Off.setText("Off");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane_Chat, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jTextField_Mensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_Destinatario)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_Enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_Status)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton_on)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton_Off)))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane_Chat, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 20, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel_Destinatario)
                    .addComponent(jLabel_Status)
                    .addComponent(jRadioButton_on)
                    .addComponent(jRadioButton_Off))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Mensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        jTabbedPane_Chat.getAccessibleContext().setAccessibleName("Chat");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList_ParticipantesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList_ParticipantesValueChanged
        String texto = jList_Participantes.getSelectedValue();
        jLabel_Destinatario.setText(texto);
    }//GEN-LAST:event_jList_ParticipantesValueChanged

    private void jButton_EnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EnviarActionPerformed
        CriarArvoreArquivos(jTextField_Mensagem.getText(), "c:/");
        jTextField_Mensagem.setText("");
    }//GEN-LAST:event_jButton_EnviarActionPerformed

    private void jTabbedPane_ChatComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTabbedPane_ChatComponentAdded
        
    }//GEN-LAST:event_jTabbedPane_ChatComponentAdded

    private void jTree_ListaArquivosValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTree_ListaArquivosValueChanged
        System.out.println(jTree_ListaArquivos.getSelectionPath());
    }//GEN-LAST:event_jTree_ListaArquivosValueChanged

    public void CriarArvoreArquivos(String nomeParticipante, String diretorio) {
        DefaultMutableTreeNode pasta = new DefaultMutableTreeNode(nomeParticipante);
        File dir = new File(diretorio);
        File[] arquivos = dir.listFiles();
        if (arquivos != null) {
            int length = arquivos.length;
            for (int i = 0; i < length; ++i) {
                File f = arquivos[i];
                System.out.println(f.getPath());
                if (f.isFile()) {
                    DefaultMutableTreeNode arquivo = new DefaultMutableTreeNode(f.getName());

                    pasta.add(arquivo);
                } else if (f.isDirectory()) {
                    System.out.println(f.getName() + " é uma pasta!");
                }
            }
        }
        //arvoreArquivos.repaint();
        raiz.add(pasta);
        jTree_ListaArquivos = new JTree(raiz);
        jScrollPane_ListaArquivos.repaint();
        jScrollPane_ListaArquivos.setViewportView(jTree_ListaArquivos);
         
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaChat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_Status;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_Enviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Destinatario;
    private javax.swing.JLabel jLabel_Status;
    private javax.swing.JList<String> jList_Participantes;
    private javax.swing.JRadioButton jRadioButton_Off;
    private javax.swing.JRadioButton jRadioButton_on;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane_Chat;
    private javax.swing.JScrollPane jScrollPane_ListaArquivos;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane_Chat;
    private javax.swing.JTextArea jTextArea_HistoricoChat;
    private javax.swing.JTextField jTextField_Mensagem;
    private javax.swing.JTree jTree_ListaArquivos;
    // End of variables declaration//GEN-END:variables
}
